
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xkalman_filter_top.h"

/*
* The configuration table for devices
*/

XKalman_filter_top_Config XKalman_filter_top_ConfigTable[XPAR_XKALMAN_FILTER_TOP_NUM_INSTANCES] =
{
	{
		XPAR_KALMAN_FILTER_TOP_0_DEVICE_ID,
		XPAR_KALMAN_FILTER_TOP_0_S_AXI_CONTROL_BUS_BASEADDR
	}
};


